name: Flutter

on:
  push:
    branches: [ master, feature/flutter-ci, fix/ci ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22'
      - run: flutter pub get
      - run: flutter update-packages
      - run: flutter build apk --debug --flavor foss
       # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: debug-apk
          path: build/app/outputs/apk/foss/debug/app-foss-debug.apk
